import json
import subprocess

import pytest
from rustic_ai.core.utils.gemstone_id import GemstoneGenerator, GemstoneID
from rustic_ai.core.utils.priority import Priority


def test_gemstone_id_go_generates_python_parses(helper_bin):
    """
    Contract test 2b.1.2 a):
    Go generates IDs with various machine_id and priority values.
    Python `GemstoneID.from_int()` parses each — extracted fields match.
    """
    req = {"count": 1000, "machine_id": 42, "priority": 2}  # Priority.NORMAL
    payload = json.dumps(req).encode("utf-8")

    result = subprocess.run(
        [str(helper_bin), "generate-gemstone-ids"], input=payload, capture_output=True
    )

    if result.returncode != 0:
        pytest.fail(f"Go binary failed: {result.stderr.decode('utf-8')}")

    go_results = json.loads(result.stdout)
    assert len(go_results) == 1000

    for go_res in go_results:
        # Parse the integer ID generated by Go using Python's parser
        py_id = GemstoneID.from_int(go_res["int_id"])

        # Assert they match
        assert py_id.priority == go_res["priority"]
        assert py_id.timestamp == go_res["timestamp"]
        assert py_id.machine_id == go_res["machine_id"]
        assert py_id.sequence_number == go_res["sequence_number"]

        # Assert the inputs were respected
        assert py_id.machine_id == 42
        assert py_id.priority == 2


def test_gemstone_id_python_generates_go_parses(helper_bin):
    """
    Contract test 2b.1.2 b):
    Reverse: Python generates 1000 IDs, Go parses them.
    """
    gen = GemstoneGenerator(99)
    py_ids = []
    int_ids = []

    for _ in range(1000):
        py_id = gen.get_id(Priority.HIGH)
        py_ids.append(py_id)
        int_ids.append(py_id.to_int())

    payload = json.dumps(int_ids).encode("utf-8")

    result = subprocess.run(
        [str(helper_bin), "parse-gemstone-ids"], input=payload, capture_output=True
    )

    if result.returncode != 0:
        pytest.fail(f"Go binary failed: {result.stderr.decode('utf-8')}")

    go_results = json.loads(result.stdout)
    assert len(go_results) == 1000

    for py_id, go_res in zip(py_ids, go_results):
        assert py_id.priority == go_res["priority"]
        assert py_id.timestamp == go_res["timestamp"]
        assert py_id.machine_id == go_res["machine_id"]
        assert py_id.sequence_number == go_res["sequence_number"]

        # Assert inputs are correct
        assert go_res["machine_id"] == 99
        assert go_res["priority"] == 2  # Priority.HIGH
